### ISSUE TITLE
ML Notebook consumes all the available memory, forcing Windows to close processes

### ISSUE THREAD

**Issue by andrasfuchs** [dotnet/csharp-notebooks#52]
The [Training and AutoML notebook](https://ntbk.io/ml-03-training) is able to consume a lot of memory, causing to hang or crash other processes.

Strangely enough, it usually works fine if you run the notebook only once. So to reproduce the problem, you should:
1. Open Windows Task Manager, and check your memory usage
2. Open [Training and AutoML notebook](https://ntbk.io/ml-03-training) 
![image](https://user-images.githubusercontent.com/910321/177153034-8b15bf0e-6137-460f-921a-969d4c95f82c.png)
3. Run it's snippets one by one, but stop at "Use AutoML to simplify trainer selection and hyper-parameter optimization."
![image](https://user-images.githubusercontent.com/910321/177153301-5fbea770-5826-411e-8240-effb40c86deb.png)
4. Run the "Use AutoML to simplify trainer selection and hyper-parameter optimization" code.
![image](https://user-images.githubusercontent.com/910321/177154184-ea393cc5-80e0-4b6c-8b0e-caed2b438b3f.png)
5. Sometimes it works fine, but last time at this point my system hang and terminated some VS processes and closed my browser unexpectedly. Memory consumption dropped back to ~950 MBs, and the notebook got into a seemingly endless loop of "Starting Kernel".
![image](https://user-images.githubusercontent.com/910321/177154469-9b3299f3-9c8e-4a4f-a732-b634b940894b.png)
6. When I tried to re-run the "Use AutoML to simplify trainer selection and hyper-parameter optimization" code snippet again, I got the following exception, repeating over and over:
![image](https://user-images.githubusercontent.com/910321/177151551-d624183e-0887-4995-81c3-6173932b65a1.png)

```
error: The JSON-RPC connection with the remote party was lost before the request could complete. 
    at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__143`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Notebook.Utils.DetectKernelStatusService.<ExecuteTaskAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Notebook.Utils.RepeatedTimeTaskService.<>c__DisplayClass7_0.<<ExecuteAsync>b__1>d.MoveNext()
```
7. If you could run the notebook without issues, try to re-run the "Use AutoML to simplify trainer selection and hyper-parameter optimization" code many times, it is inconsistent on my machine as well.

**Comment by LittleLittleCloud** [comment]
I suspect it's because the trial is still running even after that automl cell finished. Somehow AutoMLExperiment doesn't always succeed in cancelling the last running trial..

**Comment by JakeRadMSFT** [comment]
We probably also need to cleanup some things in our NotebookMonitor - 

https://github.com/dotnet/machinelearning/blob/main/src/Microsoft.ML.AutoML.Interactive/NotebookMonitor.cs

It could be holding references to a lot of things.

@andrasfuchs if you "restart kernel" does it free up the memory for you?

**Comment by andrasfuchs** [comment]
@JakeRadMSFT How can I restart the kernel?

**Comment by andrasfuchs** [comment]
I tried it again today, but after a "Run All", it got crazy again, eating up the memory and closing other running processes.

![image](https://user-images.githubusercontent.com/910321/178751135-6f335ca6-573d-4dbf-b71b-0f6868b87a0c.png)

The critical part got terminated with an exception.

![image](https://user-images.githubusercontent.com/910321/178750878-59989e83-feb8-4b74-9e9b-53ca67c0e38a.png)

The memory was not freed up after the exception, I had to close the Visual Studio process manually. 
I had no chance to test the kernel restart.

**Comment by JakeRadMSFT** [comment]
@LittleLittleCloud thoughts here?

**Comment by LittleLittleCloud** [comment]
I was thinking there's some places we forget to clear trial result and release memory (like hold all models in memory) but I didn't see the memory goes up while training. So now I suspect the crazy memory usage is caused by LightGbm trainer.

@andrasfuchs Can you try disable lgbm trainer by setting
`useLgbm: false` next to `useSdca:false`

in the following code snippet
<img width="685" alt="image" src="https://user-images.githubusercontent.com/16876986/178815835-96e499d9-dda1-4d46-bf2d-e3a363dc58b7.png">

and try the notebook again

**Comment by LittleLittleCloud** [comment]
And @JakeRadMSFT , maybe it would be helpful to add a system monitor section together with trial Monitor?

**Comment by andrasfuchs** [comment]
I got the gray rectangles instead of the results, but the memory problem seems to be better if I use `useLgbm: false`. 
![image](https://user-images.githubusercontent.com/910321/179426627-5e602c22-7466-4ac9-86fd-6a8172e04423.png)

10+ GBs of RAM usage is still a lot, I think...
![image](https://user-images.githubusercontent.com/910321/179426600-a18499fe-5e55-4385-9764-09d7ea6c795f.png)
